plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
}
dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings(loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${mappings_minecraft_version}:${mappings_version}@zip")
    })
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'

    modCompileOnly group: 'com.terraformersmc', name: 'modmenu', version: "${mod_menu_version}"
    modLocalRuntime group: 'com.terraformersmc', name: 'modmenu', version: "${mod_menu_version}"

    implementation group: 'com.electronwill.night-config', name: 'core', version: "${nightconfig_version}"
    implementation group: 'com.electronwill.night-config', name: 'toml', version: "${nightconfig_version}"
    include group: 'com.electronwill.night-config', name: 'core', version: "${nightconfig_version}"
    include group: 'com.electronwill.night-config', name: 'toml', version: "${nightconfig_version}"
}

loom {
    def aw = project(":Common").file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            source sourceSets.test
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
        }
        server {
            server()
            setConfigName("Fabric Server")
            ideConfigGenerated(true)
        }
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId project.group
            artifactId project.archivesBaseName
            version project.version
            from components.java
        }
    }
    repositories {
        if (System.getenv('local_maven') != null) {
            maven {
                url 'file://' + System.getenv('local_maven')
            }
        }
    }
}
