plugins {
    id 'multiloader-loader'
    id 'fabric-loom' version '1.6-SNAPSHOT'
}
dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'

    modCompileOnly group: 'com.terraformersmc', name: 'modmenu', version: "${mod_menu_version}"
    modLocalRuntime group: 'com.terraformersmc', name: 'modmenu', version: "${mod_menu_version}"

    implementation group: 'com.electronwill.night-config', name: 'core', version: '3.8.0'
    implementation group: 'com.electronwill.night-config', name: 'toml', version: '3.8.0'
    include group: 'com.electronwill.night-config', name: 'core', version: '3.8.0'
    include group: 'com.electronwill.night-config', name: 'toml', version: '3.8.0'
}

sourceSets {
    main {
        resources {
            srcDirs += "licenses"
        }
    }
}

loom {
    def aw = project(":common").file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            source sourceSets.test
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            runDir("runs/client")
        }
        server {
            server()
            setConfigName("Fabric Server")
            ideConfigGenerated(true)
            runDir("runs/server")
        }
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId project.group
            artifactId project.archivesBaseName
            version project.version
            from components.java
        }
    }
}
