# Gradle
org.gradle.jvmargs=-Xmx4G

# Project
version=2.1.0
group=technology.roughness.whitenoise

# Common
minecraft_version=26.1.2
mixin_extras_version=0.5.3
mixin_version=0.8.5
java_version=25
# https://central.sonatype.com/search?q=com.electronwill.night-config
nightconfig_version=3.8.4

# NeoForge
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.1.2.11-beta
neoforge_loader_version_range=[4,)
neoforge_mc_version_range=[26.1, 26.2)
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1.2-1
neogradle.subsystems.conventions.runs.create-default-run-per-type=false

# Fabric
# https://fabricmc.net/develop/
fabric_version=0.146.0+26.1.2
fabric_api_min_version=>=0.143.10
fabric_loader_version=0.19.1
fabric_loader_min_version=>=0.15
fabric_mc_version_range=[">26.1-"]
# https://www.curseforge.com/minecraft/mc-mods/modmenu/files/all
mod_menu_version=18.0.0-alpha.8

# Mod options
mod_display_name=WhiteNoise
mod_name=WhiteNoise
mod_id=whitenoise
mod_author=wendall911
mod_credits=Illusive Soulworks
license=LGPL-2.1-only
mod_description=Cross-platform library for wendall911's mods.
