# Gradle
org.gradle.jvmargs=-Xmx3G

# Project
version=0.2.1+1.18.2
group=technology.roughness.whitenoise
license=LGPL-2.1-only

# Common
minecraft_version=1.18.2

# Parchment
# https://parchmentmc.org/docs/getting-started
mappings_version=2022.11.06

# Forge
# https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=40.3.11
forge_version_range=[40,)
forge_mc_version_range=[1.18.2,1.19)

# Fabric
# https://fabricmc.net/develop/
fabric_version=0.77.0+1.18.2
fabric_mc_version_range=1.18.2
fabric_loader_version=0.14.23

# Mod options
mod_name=WhiteNoise
mod_id=whitenoise
mod_author=wendall911
mod_credits=Illusive Soulworks
mod_description=Cross-platform library for wendall911's mods.
issue_tracker=https://github.com/wendall911/WhiteNoise/issues
source=https://github.com/wendall911/WhiteNoise
