plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
}

neoForge {
    neoFormVersion = neo_form_version
    validateAccessTransformers = true
    // Automatically enable AccessTransformers if the file exists
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
}

dependencies {
    compileOnly group: 'org.spongepowered', name: 'mixin', version: "${mixin_version}"
    compileOnly group: 'com.electronwill.night-config', name: 'core', version: "${nightconfig_version}"
    compileOnly group: 'com.electronwill.night-config', name: 'toml', version: "${nightconfig_version}"
    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'
    // fabric and neoforge both bundle mixinextras, so it is safe to use it in common
    compileOnly group: 'io.github.llamalad7', name: 'mixinextras-common', version: "${mixin_extras_version}"
    annotationProcessor group: 'io.github.llamalad7', name: 'mixinextras-common', version: "${mixin_extras_version}"
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId project.group
            artifactId "whitenoise-${minecraft_version}-common"
            version project.version
            from components.java
        }
    }
    repositories {
        if (System.getenv('local_maven') != null) {
            maven {
                url 'file://' + System.getenv('local_maven')
            }
        }
    }
}
