plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

neoForge {
    version = neoforge_version
    addModdingDependenciesTo sourceSets.test
    parchment {
        minecraftVersion = minecraft_version
        mappingsVersion = mappings_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        server {
            server()
            programArgument '--nogui'
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
        "${mod_id}test" {
            sourceSet sourceSets.test
        }
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId project.group
            artifactId project.archivesBaseName
            version project.version
            // This gives us the built version NeoForge requires
            artifact jar
        }
    }
    repositories {
        if (System.getenv('local_maven') != null) {
            maven {
                url 'file://' + System.getenv('local_maven')
            }
        }
    }
}
